spring:
    application:
        name: lms
    datasource:
        url: jdbc:postgresql://localhost:5432/lms_db
        username: lms
        password: 123
    jpa:
        hibernate.ddl-auto: update
server:
    port: 8080


auth:
    secret:
        "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"